version: 1.1.1
language: "en_US"  # 从 zh_CN 改为 en_US
update_url: "https://api.github.com/repos/user/advanced-calculator/releases/latest"
logging:
  level: INFO
  file: calculator.log
history:
  max_memory: 30
  max_display: 10
  file: calc_history.json
settings:
  precision: 6
  history_size: 30
  display_size: 10
  auto_update_check: true
  complex_support: true